# ==========================================
# PATH CONFIGURATION
# ==========================================
paths:
  # dataset utama
  data_path: "artifacts/Twitter_Data.csv"

  # folder preprocessing (misal untuk save tokenizer, encoder, pembersihan teks)
  preprocessing_path: "models/preprocessing"

  # folder output model
  model_preprocess: "models/preprocessing/preprocessor.joblib"
  model_tfidf: "models/tfidf/tfidf_vectorizer.joblib"

# ==========================================
# FEATURE CONFIGURATION
# ==========================================
features:
  feature_column: "clean_text"
  target_column: "category"

# ==========================================
# MLFLOW CONFIGURATION
# ==========================================
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "sentiment_analysis_modi_category"
  artifact_path: "model"
  best_model: "sentiment_analysis_logistic_regression_optuna_best"

# ==========================================
# GENERAL EXPERIMENT SETTINGS
# ==========================================
experiment:
  name: "sentiment_analysis_modi_category"

# ============================================
# Model Configuration
# ============================================
models:
  Logistic_regression:
    enabled: true
    default_params:
      C: 1.0
      solver: "lbfgs"
      max_iter: 300

    optuna_params:
      C:
        low: 0.1
        high: 10.0
        log: true
      solver:
        choices: ["liblinear", "lbfgs", "saga"]
      max_iter:
        low: 100
        high: 500

  Naive_bayes:
    enabled: true
    default_params:
      alpha: 1.0

    optuna_params:
      alpha:
        low: 0.1
        high: 1.0

  KNN_classifier:
    enabled: true
    default_params:
      n_neighbors: 5
      weights: "distance"
      metric: "euclidean"

    optuna_params:
      n_neighbors:
        low: 3
        high: 15
      weights:
        choices: ["uniform", "distance"]
      metric:
        choices: ["euclidean", "manhattan"]

  Random_forest_classifier:
    enabled: true
    default_params:
      n_estimators: 150
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1

    optuna_params:
      n_estimators:
        low: 100
        high: 300
      max_depth:
        low: 6
        high: 20
      min_samples_split:
        low: 2
        high: 10
      min_samples_leaf:
        low: 1
        high: 4

# ============================================
# Template Prompt
# ============================================

prompt:
  predictor_prompt: |
    Context:
    {{ context }}
    You are a helpful and friendly assistant. 
    Please provide a concise and general answer to the following question:

    {% if sentiment == 0 %}
    I'm sorry, I cannot help with that.
    {% else %}
    answer the question based on the input below
    {% endif %}


    User Question:
    {{ input }}
    output :
