# ==========================================
# PATH CONFIGURATION
# ==========================================
paths:
  # dataset utama
  data_path: "artifacts/Twitter_Data.csv"

  # folder preprocessing (misal untuk save tokenizer, encoder, pembersihan teks)
  preprocessing_path: "models/preprocessing"

  # folder output model
  model_dir: "models/"

# ==========================================
# FEATURE CONFIGURATION
# ==========================================
features:
  feature_column: "clean_text"
  target_column: "category"

# ==========================================
# MLFLOW CONFIGURATION
# ==========================================
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "sentiment_analysis_modi_category"
  artifact_path: "model"

# ==========================================
# GENERAL EXPERIMENT SETTINGS
# ==========================================
experiment:
  name: "sentiment_analysis_modi_category"
